DROP TABLE IF EXISTS PRODUCTS;
DROP TABLE IF EXISTS USERS;
DROP TABLE IF EXISTS TEST_DATES;

CREATE TABLE USERS
(
    USER_ID INT NOT NULL AUTO_INCREMENT,
    USER_NAME VARCHAR(50) NOT NULL UNIQUE,
	USER_EMAIL VARCHAR(255) NOT NULL UNIQUE,
	USER_MONEY FLOAT NOT NULL,
    CONSTRAINT USER_PK PRIMARY KEY (USER_ID)
);

CREATE TABLE PRODUCTS (
	PRODUCT_ID INT NOT NULL AUTO_INCREMENT,
	PRODUCT_NAME VARCHAR(50) NOT NULL UNIQUE,
	PRODUCT_PRICE FLOAT NOT NULL,
	PRODUCT_DATE DATE NOT NULL,
	SALESMAN_ID INT NOT NULL,
	CUSTOMER_ID INT,
	CONSTRAINT PRODUCT_PK PRIMARY KEY (PRODUCT_ID),
	CONSTRAINT PRODUCT_SALESMAN_FK FOREIGN KEY (SALESMAN_ID) REFERENCES USERS(USER_ID),
	CONSTRAINT PRODUCT_CUSTOMER_FK FOREIGN KEY (CUSTOMER_ID) REFERENCES USERS(USER_ID)
);

CREATE TABLE TEST_DATES
(
    DATE_ID INT NOT NULL,
    TEST_DATE DATE NOT NULL
);

